allianceauth/authentication/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'account/login/',
        TemplateView.as_view(template_name='public/login.html'),
        name='login'
    ),
    path(
        'account/characters/main/',
        views.main_character_change,
        name='change_main_character'
    ),
    path(
        'account/characters/add/',
        views.add_character,
        name='add_character'
    ),
    path(
        'account/tokens/manage/',
        views.token_management,
        name='token_management'
    ),
    path(
        'account/tokens/delete/<int:token_id>',
        views.token_delete,
        name='token_delete'
    ),
    path(
        'account/tokens/refresh/<int:token_id>',
        views.token_refresh,
        name='token_refresh'
    ),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard_bs3/', views.dashboard_bs3, name='dashboard_bs3'),
    path('task-counts/', views.task_counts, name='task_counts'),
    path('esi-check/', views.esi_check, name='esi_check'),
]

allianceauth/notifications/urls.py
from django.urls import path
from . import views

app_name = 'notifications'
# Notifications
urlpatterns = [
    path('remove_notifications/<int:notif_id>/', views.remove_notification, name='remove'),
    path('notifications/mark_all_read/', views.mark_all_read, name='mark_all_read'),
    path('notifications/delete_all_read/', views.delete_all_read, name='delete_all_read'),
    path('notifications/', views.notification_list, name='list'),
    path('notifications/<int:notif_id>/', views.notification_view, name='view'),
    path(
        'user_notifications_count/<int:user_pk>/',
        views.user_notifications_count,
        name='user_notifications_count'
    ),
]

allianceauth/optimer/urls.py
from django.urls import path

from . import views

app_name = 'optimer'

urlpatterns = [
    path('', views.optimer_view, name='view'),
    path('add/', views.add_optimer_view, name='add'),
    path('<int:optimer_id>/remove/', views.remove_optimer, name='remove'),
    path('<int:optimer_id>/edit/', views.edit_optimer, name='edit'),
]

allianceauth/services/urls.py
from django.urls import include
from allianceauth.hooks import get_hooks
from django.urls import path

from . import views

urlpatterns = [
    # Services
    path('services/', include(([
        path('', views.services_view, name='services'),
        # Tools
        path('tool/fleet_formatter_tool/', views.fleet_formatter_view, name='fleet_format_tool'),
    ], 'services'), namespace='services')),
]

# Append hooked service urls
services = get_hooks('services_hook')
for svc in services:
    urlpatterns += svc().urlpatterns

allianceauth/srp/urls.py
from django.urls import path

from . import views

app_name = 'srp'

urlpatterns = [
    # SRP URLS
    path('', views.srp_management, name='management'),
    path('all/', views.srp_management, {'all': True}, name='all'),
    path('<int:fleet_id>/view/', views.srp_fleet_view, name='fleet'),
    path('add/', views.srp_fleet_add_view, name='add'),
    path('<int:fleet_id>/edit/', views.srp_fleet_edit_view, name='edit'),
    path('<str:fleet_srp>/request/', views.srp_request_view, name='request'),

    # SRP URLS
    path('<int:fleet_id>/remove/', views.srp_fleet_remove, name='remove'),
    path('<int:fleet_id>/disable/', views.srp_fleet_disable, name='disable'),
    path('<int:fleet_id>/enable/', views.srp_fleet_enable, name='enable'),
    path('<int:fleet_id>/complete/', views.srp_fleet_mark_completed,
        name='mark_completed'),
    path('<int:fleet_id>/incomplete/', views.srp_fleet_mark_uncompleted,
        name='mark_uncompleted'),
    path('request/remove/', views.srp_request_remove,
        name="request_remove"),
    path('request/approve/', views.srp_request_approve,
        name='request_approve'),
    path('request/reject/', views.srp_request_reject,
        name='request_reject'),
    path('request/<int:fleet_srp_request_id>/update/', views.srp_request_update_amount,
        name="request_update_amount"),
]

allianceauth/urls.py
from typing import List, Iterable, Callable

from django.urls import include
import esi.urls
from django.conf import settings
from django.contrib import admin
from django.urls import URLPattern, include, path
from django.views.generic.base import TemplateView

import allianceauth.authentication.urls
import allianceauth.authentication.views
import allianceauth.groupmanagement.urls
import allianceauth.notifications.urls
import allianceauth.services.urls
from allianceauth import NAME, views
from allianceauth.authentication import hmac_urls
from allianceauth.authentication.decorators import (
    decorate_url_patterns,
    main_character_required
)
from allianceauth.hooks import get_hooks

admin.site.site_header = NAME


def urls_from_apps(
    apps_hook_functions: Iterable[Callable], public_views_allowed: List[str]
) -> List[URLPattern]:
    """Return urls from apps and add default decorators."""

    url_patterns = []
    allowed_apps = set(public_views_allowed)
    for app_hook_function in apps_hook_functions:
        url_hook = app_hook_function()
        app_pattern = url_hook.include_pattern
        excluded_views = (
            url_hook.excluded_views
            if app_pattern.app_name in allowed_apps
            else None
        )
        url_patterns += [
            path(
                "",
                decorate_url_patterns(
                    [app_pattern], main_character_required, excluded_views
                )
            )
        ]

    return url_patterns


# Functional/Untranslated URL's
urlpatterns = [
    # Locale
    path('i18n/', include('django.conf.urls.i18n')),

    # Authentication
    path('', include(allianceauth.authentication.urls)),
    path('account/login/', TemplateView.as_view(template_name='public/login.html'), name='auth_login_user'),
    path('account/', include(hmac_urls)),

    # Admin urls
    path('admin/', admin.site.urls),

    # SSO
    path('sso/', include((esi.urls, 'esi'), namespace='esi')),
    path('sso/login', allianceauth.authentication.views.sso_login, name='auth_sso_login'),

    # Notifications
    path('', include(allianceauth.notifications.urls)),

    # Groups
    path('', include(allianceauth.groupmanagement.urls)),

    # Services
    path('', decorate_url_patterns(allianceauth.services.urls.urlpatterns, main_character_required)),

    # Night mode
    path('night/', views.NightModeRedirectView.as_view(), name='nightmode'),

    # Theme Change
    path('theme/', views.ThemeRedirectView.as_view(), name='theme')
]

url_hooks = get_hooks("url_hook")
public_views_allows = getattr(settings, "APPS_WITH_PUBLIC_VIEWS", [])
urlpatterns += urls_from_apps(url_hooks, public_views_allows)

allianceauth/analytics/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from uuid import uuid4


class AnalyticsIdentifier(models.Model):

    identifier = models.UUIDField(
        default=uuid4,
        editable=False)

    def save(self, *args, **kwargs):
        if not self.pk and AnalyticsIdentifier.objects.exists():
            # Force a single object
            raise ValidationError('There is can be only one \
                                    AnalyticsIdentifier instance')
        self.pk = self.id = 1  # If this happens to be deleted and recreated, force it to be 1
        return super().save(*args, **kwargs)


class AnalyticsTokens(models.Model):

    class Analytics_Type(models.TextChoices):
        GA_U = 'GA-U', _('Google Analytics Universal')
        GA_V4 = 'GA-V4', _('Google Analytics V4')

    name = models.CharField(max_length=254)
    type = models.CharField(max_length=254, choices=Analytics_Type.choices)
    token = models.CharField(max_length=254, blank=False)
    secret = models.CharField(max_length=254, blank=True)
    send_stats = models.BooleanField(default=False)

allianceauth/authentication/models.py
import logging

from django.contrib.auth.models import User, Permission
from django.db import models, transaction
from django.utils.translation import gettext_lazy as _
from allianceauth.eveonline.models import EveCharacter, EveCorporationInfo, EveAllianceInfo, EveFactionInfo
from allianceauth.notifications import notify
from django.conf import settings

from .managers import CharacterOwnershipManager, StateManager

logger = logging.getLogger(__name__)


class State(models.Model):
    name = models.CharField(max_length=32, unique=True)
    permissions = models.ManyToManyField(Permission, blank=True)
    priority = models.IntegerField(unique=True, help_text="Users get assigned the state with the highest priority available to them.")

    member_characters = models.ManyToManyField(EveCharacter, blank=True,
                                                help_text="Characters to which this state is available.")
    member_corporations = models.ManyToManyField(EveCorporationInfo, blank=True,
                                                help_text="Corporations to whose members this state is available.")
    member_alliances = models.ManyToManyField(EveAllianceInfo, blank=True,
                                            help_text="Alliances to whose members this state is available.")
    member_factions = models.ManyToManyField(EveFactionInfo, blank=True,
                                            help_text="Factions to whose members this state is available.")
    public = models.BooleanField(default=False, help_text="Make this state available to any character.")

    objects = StateManager()

    class Meta:
        ordering = ['-priority']

    def __str__(self):
        return self.name

    def available_to_character(self, character):
        return self in State.objects.available_to_character(character)

    def available_to_user(self, user):
        return self in State.objects.available_to_user(user)

    def delete(self, **kwargs):
        with transaction.atomic():
            for profile in self.userprofile_set.all():
                profile.assign_state(state=State.objects.exclude(pk=self.pk).get_for_user(profile.user))
        super().delete(**kwargs)


def get_guest_state():
    try:
        return State.objects.get(name='Guest')
    except State.DoesNotExist:
        return State.objects.create(name='Guest', priority=0, public=True)


def get_guest_state_pk():
    return get_guest_state().pk


class UserProfile(models.Model):
    class Meta:
        default_permissions = ('change',)

    class Language(models.TextChoices):
        """
        Choices for UserProfile.language
        """
        # Sorted by Language Code alphabetical order + English at top
        ENGLISH = 'en', _('English')
        CZECH = 'cs-cz', _("Czech")  # Not yet at 50% translated
        GERMAN = 'de', _('German')
        SPANISH = 'es', _('Spanish')
        ITALIAN = 'it-it', _('Italian')
        JAPANESE = 'ja', _('Japanese')
        KOREAN = 'ko-kr', _('Korean')
        FRENCH = 'fr-fr', _('French')
        RUSSIAN = 'ru', _('Russian')
        DUTCH = 'nl-nl', _("Dutch")
        POLISH = 'pl-pl', _("Polish")
        UKRAINIAN = 'uk', _('Ukrainian')
        CHINESE = 'zh-hans', _('Simplified Chinese')

    user = models.OneToOneField(
        User,
        related_name='profile',
        on_delete=models.CASCADE)
    main_character = models.OneToOneField(
        EveCharacter,
        blank=True,
        null=True,
        on_delete=models.SET_NULL)
    state = models.ForeignKey(
        State,
        on_delete=models.SET_DEFAULT,
        default=get_guest_state_pk)
    language = models.CharField(
        _("Language"), max_length=10,
        choices=Language.choices,
        blank=True,
        default='')
    night_mode = models.BooleanField(
        _("Night Mode"),
        blank=True,
        null=True)
    theme = models.CharField(
        _("Theme"),
        max_length=200,
        blank=True,
        null=True,
        help_text="Bootstrap 5 Themes from https://bootswatch.com/ or Community Apps"
    )

    def assign_state(self, state=None, commit=True):
        if not state:
            state = State.objects.get_for_user(self.user)
        if self.state != state:
            self.state = state
            if commit:
                logger.info(f'Updating {self.user} state to {self.state}')
                self.save(update_fields=['state'])
                notify(
                    self.user,
                    _('State changed to: %s' % state),
                    _('Your user\'s state is now: %(state)s')
                    % ({'state': state}),
                    'info'
                )
                from allianceauth.authentication.signals import state_changed

                # We need to ensure we get up to date perms here as they will have just changed.
                # Clear all attribute caches and reload the model that will get passed to the signals!
                self.refresh_from_db()

                state_changed.send(
                    sender=self.__class__, user=self.user, state=self.state
                )

    def __str__(self):
        return str(self.user)
class CharacterOwnership(models.Model):
    class Meta:
        default_permissions = ('change', 'delete')
        ordering = ['user', 'character__character_name']

    character = models.OneToOneField(EveCharacter, on_delete=models.CASCADE, related_name='character_ownership')
    owner_hash = models.CharField(max_length=28, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='character_ownerships')

    objects = CharacterOwnershipManager()

    def __str__(self):
        return f"{self.user}: {self.character}"


class OwnershipRecord(models.Model):
    character = models.ForeignKey(EveCharacter, on_delete=models.CASCADE, related_name='ownership_records')
    owner_hash = models.CharField(max_length=28, db_index=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ownership_records')
    created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f"{self.user}: {self.character} on {self.created}"

allianceauth/fleetactivitytracking/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from allianceauth.eveonline.models import EveCharacter
from allianceauth.framework.api.user import get_sentinel_user


class Fatlink(models.Model):
    fatdatetime = models.DateTimeField(default=timezone.now)
    duration = models.PositiveIntegerField()
    fleet = models.CharField(max_length=254)
    hash = models.CharField(max_length=254, unique=True)
    creator = models.ForeignKey(User, on_delete=models.SET(get_sentinel_user))

    def __str__(self):
        return self.fleet


class Fat(models.Model):
    character = models.ForeignKey(EveCharacter, on_delete=models.CASCADE)
    fatlink = models.ForeignKey(Fatlink, on_delete=models.CASCADE)
    system = models.CharField(max_length=30)
    shiptype = models.CharField(max_length=100)
    station = models.CharField(max_length=125)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('character', 'fatlink'),)

    def __str__(self):
        return "Fat-link for %s" % self.character.character_name

allianceauth/optimer/models.py
from datetime import datetime

from django.db import models
from django.utils import timezone

from allianceauth.eveonline.models import EveCharacter


class OpTimerType(models.Model):
    """
    Optimer Type
    """

    type = models.CharField(max_length=254, default="")

    def __str__(self):
        return self.type

    class Meta:
        ordering = ['type']
        default_permissions = ()


class OpTimer(models.Model):
    class Meta:
        ordering = ['start']
        default_permissions = ()

    doctrine = models.CharField(max_length=254, default="")
    system = models.CharField(max_length=254, default="")
    start = models.DateTimeField(default=datetime.now)
    duration = models.CharField(max_length=25, default="")
    operation_name = models.CharField(max_length=254, default="")
    fc = models.CharField(max_length=254, default="")
    post_time = models.DateTimeField(default=timezone.now)
    eve_character = models.ForeignKey(EveCharacter, null=True,
                                    on_delete=models.SET_NULL)
    description = models.TextField(blank=True, default="")
    type = models.ForeignKey(OpTimerType, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.operation_name

allianceauth/permissions_tool/models.py
from django.db import models


class PermissionsTool(models.Model):
    """
    Dummy model for holding permissions
    """
    class Meta:
        managed = False
        permissions = (
            ('audit_permissions', 'Can audit permissions'),
        )

allianceauth/services/modules/discourse/models.py
from django.contrib.auth.models import User
from django.db import models


class DiscourseUser(models.Model):
    user = models.OneToOneField(User,
                                primary_key=True,
                                on_delete=models.CASCADE,
                                related_name='discourse')
    enabled = models.BooleanField()

    def __str__(self):
        return self.user.username

    class Meta:
        permissions = (
            ("access_discourse", "Can access the Discourse service"),
        )

allianceauth/templates/allianceauth/base-bs5.html
{% load static %}
{% load i18n %}
{% load navactive %}
{% load auth_notifications %}
{% load theme_tags %}
<!DOCTYPE html>
<html lang="en" {% theme_html_tags %}>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- End Required meta tags -->

        <!-- Meta tags -->
        <!-- TODO Bundle all the site specific stuff up into its own template for easy override -->
        <meta name="description" content="">
        <meta name="author" content="">
        {% include 'allianceauth/icons.html' %}
        <!-- Meta tags -->
        <title>{% block title %}{% block page_title %}{% endblock page_title %} - {{ SITE_NAME }}{% endblock title %}</title>

        {% theme_css %}

        {% include 'bundles/fontawesome.html' %}
        {% include 'bundles/auth-framework-css.html' %}

        <style>
            .navbar-toggler.collapsed{
                transform: rotate(180deg);
            }

            .nav-padding {
                padding-top: {% header_padding_size %} !important;
            }
        </style>

        {% block extra_css %}{% endblock extra_css %}

        {% include 'custom_css/bundles/custom-css.html' %}
    </head>

    <body>
        <!-- Top Menu, Blocks don't work in "include" tagged views -->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-primary">
            <div class="container-fluid justify-content-start">
                <a class="navbar-brand" data-bs-toggle="collapse" data-bs-target="#sidebar" role="button">
                    <i class="fa-solid fa-bars ms-2 me-2"></i>
                </a>

                <div class="navbar-brand">
                    {% block header_nav_brand %}{{ SITE_NAME }}{% endblock %}
                </div>

                <div class="collapse navbar-collapse ms-2 px-2" id="navbarexpand">
                    <ul id="nav-left" class="nav navbar-nav me-auto">
                        {% block header_nav_collapse_left %}
                        {% endblock %}
                    </ul>

                    <ul id="nav-right" class="nav navbar-nav">
                        {% block header_nav_collapse_right %}
                        {% endblock %}
                    </ul>

                    <ul id="nav-right-character-control" class="nav navbar-nav">
                        {% block header_nav_user_character_control %} <!-- Default to add char and swap main -->
                            {% include 'allianceauth/top-menu-rh-default.html' %}
                        {% endblock %}

                        {% if user.is_authenticated %}
                            {% include 'menu/menu-notification-block.html' %}
                        {% endif %}
                    </ul>
                </div>

                <a class="navbar-toggler navbar-brand border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#navbarexpand" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation" style="margin-left: auto;">
                    <i class="fa-solid fa-chevron-up"></i>
                </a>
            </div>
        </nav>
        <!-- End Top Menu -->

        <!-- Body -->
        <main class="row flex-nowrap m-0">
            {% include 'menu/sortable-side-menu.html' %}

            <div class="nav-padding col flex-nowrap vh-100 overflow-auto">
                <div class="my-3">
                    {% include 'allianceauth/messages-bs5.html' %}

                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </main>
        <!-- End Body -->

        <script>
            (() => {
                // TODO Move to own JS file
                const sidebar = document.getElementById('sidebar');

                sidebar.addEventListener('shown.bs.collapse', () => {
                    localStorage.removeItem('sidebar_' + sidebar.id);
                });

                sidebar.addEventListener('hidden.bs.collapse', () => {
                    localStorage.setItem('sidebar_' + sidebar.id, 'closed');
                });

                if (localStorage.getItem('sidebar_' + sidebar.id) === 'closed') {
                    sidebar.classList.remove('show')
                } else {
                    sidebar.classList.add("show")
                }

                const activeChildMenuItem = document.querySelector('#sidebar-menu li ul li a.active');
                if (activeChildMenuItem) {
                    activeChildMenuItem.parentElement.parentElement.classList.add('show');
                }
            })();
        </script>

        {% include 'bundles/jquery-js.html' %}
        {% theme_js %}

        {% if user.is_authenticated %}
            <script>
                const notificationUpdateSettings = {
                    refreshTime: "{% notifications_refresh_time %}",
                    userNotificationsCountViewUrl: "{% url 'notifications:user_notifications_count' request.user.pk %}"
                };
            </script>

            {% include 'bundles/refresh-notification-icon-js.html' %}
        {% endif %}

        {% block extra_javascript %}
        {% endblock extra_javascript %}
        <script>
            {% block extra_script %}
            {% endblock extra_script %}
        </script>
    </body>
</html>

allianceauth/templates/allianceauth/base.html
{% load i18n %}
{% load navactive %}
{% load auth_notifications %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        {% include 'allianceauth/icons.html' %}

        <title>{% block title %}{% block page_title %}{% endblock page_title %} - {{ SITE_NAME }}{% endblock title %}</title>

        {% include 'bundles/bootstrap-css.html' %}
        {% include 'bundles/fontawesome.html' %}
        {% include 'bundles/auth-base-css.html' %}

        {% block extra_css %}{% endblock extra_css %}
    </head>

    <body class="{% if NIGHT_MODE %}template-dark-mode{% else %}template-light-mode{% endif %}">
        <div id="wrapper" class="container">
            <!-- Navigation -->
            {% include 'allianceauth/top-menu.html' %}

            <div class="clearfix{% if user.is_authenticated %} row{% endif %}" id="site-body-wrapper">
                {% if user.is_authenticated %}
                    {% include 'allianceauth/side-menu.html' %}
                {% endif %}

                <div class="{% if user.is_authenticated %}col-sm-10{% else %}col-sm-12{% endif %}">
                    {% include 'allianceauth/messages.html' %}

                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </div>

        {% include 'bundles/bootstrap-js.html' %}
        {% include 'bundles/jquery-visibility-js.html' %}

        {% if user.is_authenticated %}
            <script>
                let notificationUPdateSettings = {
                    notificationsListViewUrl: "{% url 'notifications:list' %}",
                    notificationsRefreshTime: "{% notifications_refresh_time %}",
                    userNotificationsCountViewUrl: "{% url 'notifications:user_notifications_count' request.user.pk %}"
                };
            </script>
            {% include 'bundles/refresh-notifications-js.html' %}
        {% endif %}
        {% include 'bundles/evetime-js.html' %}

        {% block extra_javascript %}
        {% endblock extra_javascript %}
        <script>
            {% block extra_script %}
            {% endblock extra_script %}
        </script>
    </body>
</html>

allianceauth/templates/allianceauth/icons.html
{% load static %}

<link rel="apple-touch-icon" sizes="180x180" href="{% static 'allianceauth/icons/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" href="{% static 'allianceauth/icons/favicon-16x16.png' %}" sizes="16x16">
<link rel="icon" type="image/png" href="{% static 'allianceauth/icons/favicon-32x32.png' %}" sizes="32x32">
<link rel="icon" type="image/png" href="{% static 'allianceauth/icons/favicon-96x96.png' %}" sizes="96x96">
<link rel="manifest" href="{% static 'allianceauth/icons/site.webmanifest' %}">
<link rel="mask-icon" href="{% static 'allianceauth/icons/safari-pinned-tab.svg' %}" color="#5bbad5">
<link rel="shortcut icon" type="image/png" href="{% static 'allianceauth/icons/favicon.ico' %}">

<meta name="msapplication-TileColor" content="#2d89ef">
<meta name="msapplication-config" content="{% static 'allianceauth/icons/browserconfig.xml' %}">
<meta name="theme-color" content="#ffffff">

allianceauth/templates/allianceauth/night-toggle.html
{% load i18n %}

<li>
    <a href="{% url 'nightmode' %}?next={{ request.path|urlencode }}">
        <i class="fa-solid {% if NIGHT_MODE %}fa-toggle-on{% else %}fa-toggle-off{% endif %}" aria-hidden="true"></i>
        {% translate "Night Mode" %}
    </a>
</li>

allianceauth/templates/allianceauth/notifications_menu_item.html
{% load i18n %}
{% load auth_notifications %}

{% with unread_count=request.user|user_unread_notification_count %}
    {% if unread_count > 0 %}
        <a href="{% url 'notifications:list' %}">{% translate "Notifications" %}
            <span class="badge">{{ unread_count }}</span>
        </a>
    {% else %}
        <a href="{% url 'notifications:list' %}">
            <i class="fa-solid fa-bell"></i>
        </a>
    {% endif %}
{% endwith %}

allianceauth/templates/allianceauth/top-menu-rh-default.html
{% load i18n %}
{% if user.is_authenticated %}
<li class="nav-item">
    <a href="{% url 'authentication:add_character' %}" class="nav-link" title="{% translate 'Add Character' %}">
        <i class="fa-solid fa-plus"></i>
        <span class="d-lg-none d-md-inline m-2">{% translate "Add Character" %}</span>
    </a>
</li>
<li class="nav-item">
    <a href="{% url 'authentication:change_main_character' %}" class="nav-link" title="{% translate 'Change Main' %}">
        <i class="fa-solid fa-shuffle"></i>
        <span class="d-lg-none d-md-inline m-2">{% translate "Change Main" %}</span>
    </a>
</li>
{% else %}
<li class="nav-item">
    <a href="{% url 'authentication:login' %}" class="nav-link" title="{% translate 'Sign In' %}">
        <i class="fa-solid fa-right-to-bracket fa-fw "></i> {% translate "Sign In" %}
    </a>
</li>
{% endif %}

allianceauth/templates/allianceauth/top-menu-user-dropdown.html
{% load i18n %}
{% load evelinks %}

<li class="top-user-menu dropdown{% if request.user.profile.main_character %} with-main-character{% endif %}">
    <a href="#" class="dropdown-toggle" type="button" id="top-user-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        {% if request.user.profile.main_character %}
            {% with request.user.profile.main_character as main %}
                <img class="img-rounded ra-avatar" src="{{ main.character_id|character_portrait_url:32 }}" alt="{{ main.character_name }}">
                <span class="hidden-sm hidden-md hidden-lg">
                    {{ main.character_name }} - {% translate "User Menu" %}
                </span>
            {% endwith %}
        {% else %}
            <img class="img-rounded ra-avatar" src="{{ 1|character_portrait_url:32 }}" alt="{{ main.character_name }}">
            <span class="hidden-sm hidden-md hidden-lg">
                    {% translate "User Menu" %}
                </span>
        {% endif %}
        <span class="caret"></span>
    </a>

    <ul class="dropdown-menu top-user-menu" aria-labelledby="top-user-menu">
        <!-- user avatar -->
        {% if request.user.profile.main_character %}
            <li>
                {% with request.user.profile.main_character as main %}
                    <p class="text-center">
                        <img class="img-rounded ra-avatar" src="{{ main.character_id|character_portrait_url:256 }}" alt="{{ main.character_name }}">
                    </p>

                    <p class="text-center">
                        <span style="display: block;">{{ main.character_name }}</span>
                        <span style="display: block;">{{ main.corporation_name }}</span>

                        {% if main.alliance_name %}
                            <span style="display: block;">{{ main.alliance_name }}</span>
                        {% endif %}
                    </p>
                {% endwith %}
            </li>
            <li role="separator" class="divider"></li>
        {% endif %}

        <li class="top-menu-bar-language-select">
            {% include 'public/lang_select.html' %}
        </li>

        <li role="separator" class="divider"></li>

        <!-- night mode toggle -->
        {% include 'allianceauth/night-toggle.html' %}

        <!-- admin related menu items -->
        {% include 'allianceauth/top-menu-admin.html' %}

        <!-- logout / login -->
        <li role="separator" class="divider"></li>
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'authentication:token_management' %}">
                    <i class="fa-solid fa-user-lock"></i>
                    {% translate "Token Management" %}
                </a>
            </li>
            <li role="separator" class="divider"></li>

            <li><a href="{% url 'logout' %}">{% translate "Logout" %}</a></li>
        {% else %}
            <li><a href="{% url 'authentication:login' %}">{% translate "Login" %}</a></li>
        {% endif %}
    </ul>
</li>