allianceauth/hrapplications/urls.py
from django.urls import path

from . import views

app_name = 'hrapplications'

urlpatterns = [
    path('', views.hr_application_management_view,
        name="index"),
    path('create/', views.hr_application_create_view,
        name="create_view"),
    path('create/<int:form_id>/', views.hr_application_create_view,
        name="create_view"),
    path('remove/<int:app_id>/', views.hr_application_remove,
        name="remove"),
    path('view/<int:app_id>/', views.hr_application_view,
        name="view"),
    path('personal/view/<int:app_id>/', views.hr_application_personal_view,
        name="personal_view"),
    path('personal/removal/<int:app_id>/',
        views.hr_application_personal_removal,
        name="personal_removal"),
    path('approve/<int:app_id>/', views.hr_application_approve,
        name="approve"),
    path('reject/<int:app_id>/', views.hr_application_reject,
        name="reject"),
    path('search/', views.hr_application_search,
        name="search"),
    path('mark_in_progress/<int:app_id>/', views.hr_application_mark_in_progress,
        name="mark_in_progress"),
]

allianceauth/urls.py
from typing import List, Iterable, Callable

from django.urls import include
import esi.urls
from django.conf import settings
from django.contrib import admin
from django.urls import URLPattern, include, path
from django.views.generic.base import TemplateView

import allianceauth.authentication.urls
import allianceauth.authentication.views
import allianceauth.groupmanagement.urls
import allianceauth.notifications.urls
import allianceauth.services.urls
from allianceauth import NAME, views
from allianceauth.authentication import hmac_urls
from allianceauth.authentication.decorators import (
    decorate_url_patterns,
    main_character_required
)
from allianceauth.hooks import get_hooks

admin.site.site_header = NAME


def urls_from_apps(
    apps_hook_functions: Iterable[Callable], public_views_allowed: List[str]
) -> List[URLPattern]:
    """Return urls from apps and add default decorators."""

    url_patterns = []
    allowed_apps = set(public_views_allowed)
    for app_hook_function in apps_hook_functions:
        url_hook = app_hook_function()
        app_pattern = url_hook.include_pattern
        excluded_views = (
            url_hook.excluded_views
            if app_pattern.app_name in allowed_apps
            else None
        )
        url_patterns += [
            path(
                "",
                decorate_url_patterns(
                    [app_pattern], main_character_required, excluded_views
                )
            )
        ]

    return url_patterns


# Functional/Untranslated URL's
urlpatterns = [
    # Locale
    path('i18n/', include('django.conf.urls.i18n')),

    # Authentication
    path('', include(allianceauth.authentication.urls)),
    path('account/login/', TemplateView.as_view(template_name='public/login.html'), name='auth_login_user'),
    path('account/', include(hmac_urls)),

    # Admin urls
    path('admin/', admin.site.urls),

    # SSO
    path('sso/', include((esi.urls, 'esi'), namespace='esi')),
    path('sso/login', allianceauth.authentication.views.sso_login, name='auth_sso_login'),

    # Notifications
    path('', include(allianceauth.notifications.urls)),

    # Groups
    path('', include(allianceauth.groupmanagement.urls)),

    # Services
    path('', decorate_url_patterns(allianceauth.services.urls.urlpatterns, main_character_required)),

    # Night mode
    path('night/', views.NightModeRedirectView.as_view(), name='nightmode'),

    # Theme Change
    path('theme/', views.ThemeRedirectView.as_view(), name='theme')
]

url_hooks = get_hooks("url_hook")
public_views_allows = getattr(settings, "APPS_WITH_PUBLIC_VIEWS", [])
urlpatterns += urls_from_apps(url_hooks, public_views_allows)

allianceauth/hrapplications/models.py
from django.contrib.auth.models import User
from django.db import models
from sortedm2m.fields import SortedManyToManyField

from allianceauth.eveonline.models import EveCharacter, EveCorporationInfo

from .managers import ApplicationManager


class ApplicationQuestion(models.Model):
    title = models.CharField(max_length=254, verbose_name='Question')
    help_text = models.CharField(max_length=254, blank=True, null=True)
    multi_select = models.BooleanField(default=False)

    def __str__(self):
        return "Question: " + self.title


class ApplicationChoice(models.Model):
    question = models.ForeignKey(ApplicationQuestion,on_delete=models.CASCADE,related_name="choices")
    choice_text = models.CharField(max_length=200, verbose_name='Choice')

    def __str__(self):
        return self.choice_text


class ApplicationForm(models.Model):
    questions = SortedManyToManyField(ApplicationQuestion)
    corp = models.OneToOneField(EveCorporationInfo, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.corp)


class Application(models.Model):
    form = models.ForeignKey(ApplicationForm, on_delete=models.CASCADE, related_name='applications')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='applications')
    approved = models.BooleanField(blank=True, null=True, default=None)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    reviewer_character = models.ForeignKey(EveCharacter, on_delete=models.SET_NULL, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ApplicationManager()

    def __str__(self):
        return str(self.user) + " Application To " + str(self.form)

    class Meta:
        permissions = (
            ('approve_application', 'Can approve applications'), ('reject_application', 'Can reject applications'),
            ('view_apis', 'Can view applicant APIs'),)
        unique_together = ('form', 'user')

    @property
    def main_character(self):
        return self.user.profile.main_character

    @property
    def characters(self):
        return [o.character for o in self.user.character_ownerships.all()]

    @property
    def reviewer_str(self):
        if self.reviewer_character:
            return str(self.reviewer_character)
        elif self.reviewer:
            return "User " + str(self.reviewer)
        else:
            return None


class ApplicationResponse(models.Model):
    question = models.ForeignKey(ApplicationQuestion, on_delete=models.CASCADE)
    application = models.ForeignKey(Application, on_delete=models.CASCADE, related_name='responses')
    answer = models.TextField()

    def __str__(self):
        return str(self.application) + " Answer To " + str(self.question)

    class Meta:
        unique_together = ('question', 'application')


class ApplicationComment(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + " comment on " + str(self.application)

allianceauth/hrapplications/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class HRApplicationCommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea, required=False, label=_("Comment"))


class HRApplicationSearchForm(forms.Form):
    search_string = forms.CharField(max_length=254, required=True, label=_("Search String"))

allianceauth/hrapplications/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, get_object_or_404, redirect, Http404
from django.db.models import Q
from .models import Application
from .models import ApplicationComment
from .models import ApplicationForm
from .models import ApplicationResponse
from allianceauth.notifications import notify

from .forms import HRApplicationCommentForm
from .forms import HRApplicationSearchForm

logger = logging.getLogger(__name__)


def create_application_test(user):
    return bool(user.profile.main_character)


@login_required
def hr_application_management_view(request):
    logger.debug("hr_application_management_view called by user %s" % request.user)
    corp_applications = []
    finished_corp_applications = []
    main_char = request.user.profile.main_character

    base_app_query = Application.objects.select_related('user', 'form', 'form__corp')
    if request.user.is_superuser:
        corp_applications = base_app_query.filter(approved=None).order_by('-created')
        finished_corp_applications = base_app_query.exclude(approved=None).order_by('-created')
    elif request.user.has_perm('auth.human_resources') and main_char:
        if ApplicationForm.objects.filter(corp__corporation_id=main_char.corporation_id).exists():
            app_form = ApplicationForm.objects.get(corp__corporation_id=main_char.corporation_id)
            corp_applications = base_app_query.filter(form=app_form).filter(approved=None).order_by('-created')
            finished_corp_applications = base_app_query.filter(form=app_form).filter(
                approved__in=[True, False]).order_by('-created')
    logger.debug("Retrieved {} personal, {} corp applications for {}".format(
        len(request.user.applications.all()), len(corp_applications), request.user))
    context = {
        'personal_apps': request.user.applications.all(),
        'applications': corp_applications,
        'finished_applications': finished_corp_applications,
        'search_form': HRApplicationSearchForm(),
        'create': create_application_test(request.user)
    }
    return render(request, 'hrapplications/management.html', context=context)


@login_required
@user_passes_test(create_application_test)
def hr_application_create_view(request, form_id=None):
    if form_id:
        app_form = get_object_or_404(ApplicationForm, id=form_id)
        if request.method == "POST":
            if Application.objects.filter(user=request.user).filter(form=app_form).exists():
                logger.warning(f"User {request.user} attempting to duplicate application to {app_form.corp}")
            else:
                application = Application(user=request.user, form=app_form)
                application.save()
                for question in app_form.questions.all():
                    response = ApplicationResponse(question=question, application=application)
                    response.answer = "\n".join(request.POST.getlist(str(question.pk), ""))
                    response.save()
                logger.info(f"{request.user} created {application}")
            return redirect('hrapplications:personal_view', application.id)
        else:
            questions = app_form.questions.all()
            return render(request, 'hrapplications/create.html', context={'questions': questions, 'corp': app_form.corp})
    else:
        choices = []
        for app_form in ApplicationForm.objects.all():
            if not Application.objects.filter(user=request.user).filter(form=app_form).exists():
                choices.append((app_form.id, app_form.corp.corporation_name))
        return render(request, 'hrapplications/corpchoice.html', context={'choices': choices})


@login_required
def hr_application_personal_view(request, app_id):
    logger.debug(f"hr_application_personal_view called by user {request.user} for app id {app_id}")
    app = get_object_or_404(Application, pk=app_id)
    if app.user == request.user:
        context = {
            'app': app,
            'responses': ApplicationResponse.objects.filter(application=app),
            'buttons': False,
            'comments': ApplicationComment.objects.filter(application=app),
            'comment_form': HRApplicationCommentForm(),
        }
        return render(request, 'hrapplications/view.html', context=context)
    else:
        logger.warning(f"User {request.user} not authorized to view {app}")
        return redirect('hrapplications:personal_view')


@login_required
def hr_application_personal_removal(request, app_id):
    logger.debug(f"hr_application_personal_removal called by user {request.user} for app id {app_id}")
    app = get_object_or_404(Application, pk=app_id)
    if app.user == request.user:
        if app.approved is None:
            logger.info(f"User {request.user} deleting {app}")
            app.delete()
        else:
            logger.warning(f"User {request.user} attempting to delete reviewed app {app}")
    else:
        logger.warning(f"User {request.user} not authorized to delete {app}")
    return redirect('hrapplications:index')


@login_required
@permission_required('auth.human_resources')
def hr_application_view(request, app_id):
    logger.debug(f"hr_application_view called by user {request.user} for app id {app_id}")
    try:
        app = Application.objects.prefetch_related('responses', 'comments', 'comments__user').get(pk=app_id)
    except Application.DoesNotExist:
        raise Http404
    if request.method == 'POST':
        if request.user.has_perm('hrapplications.add_applicationcomment'):
            form = HRApplicationCommentForm(request.POST)
            logger.debug("Request type POST contains form valid: %s" % form.is_valid())
            if form.is_valid():
                comment = ApplicationComment()
                comment.application = app
                comment.user = request.user
                comment.text = form.cleaned_data['comment']
                comment.save()
                logger.info(f"Saved comment by user {request.user} to {app}")
                return redirect('hrapplications:view', app_id)
        else:
            logger.warning("User %s does not have permission to add ApplicationComments" % request.user)
            return redirect('hrapplications:view', app_id)
    else:
        logger.debug("Returning blank HRApplication comment form.")
        form = HRApplicationCommentForm()
    context = {
        'app': app,
        'responses': app.responses.all(),
        'buttons': True,
        'comments': app.comments.all(),
        'comment_form': form,
    }
    return render(request, 'hrapplications/view.html', context=context)


@login_required
@permission_required('auth.human_resources')
@permission_required('hrapplications.delete_application')
def hr_application_remove(request, app_id):
    logger.debug(f"hr_application_remove called by user {request.user} for app id {app_id}")
    app = get_object_or_404(Application, pk=app_id)
    logger.info(f"User {request.user} deleting {app}")
    app.delete()
    notify(app.user, "Application Deleted", message="Your application to %s was deleted." % app.form.corp)
    return redirect('hrapplications:index')


@login_required
@permission_required('auth.human_resources')
@permission_required('hrapplications.approve_application')
def hr_application_approve(request, app_id):
    logger.debug(f"hr_application_approve called by user {request.user} for app id {app_id}")
    app = get_object_or_404(Application, pk=app_id)
    if request.user.is_superuser or request.user == app.reviewer:
        logger.info(f"User {request.user} approving {app}")
        app.approved = True
        app.save()
        notify(app.user, "Application Accepted", message="Your application to %s has been approved." % app.form.corp, level="success")
    else:
        logger.warning(f"User {request.user} not authorized to approve {app}")
    return redirect('hrapplications:index')


@login_required
@permission_required('auth.human_resources')
@permission_required('hrapplications.reject_application')
def hr_application_reject(request, app_id):
    logger.debug(f"hr_application_reject called by user {request.user} for app id {app_id}")
    app = get_object_or_404(Application, pk=app_id)
    if request.user.is_superuser or request.user == app.reviewer:
        logger.info(f"User {request.user} rejecting {app}")
        app.approved = False
        app.save()
        notify(app.user, "Application Rejected", message="Your application to %s has been rejected." % app.form.corp, level="danger")
    else:
        logger.warning(f"User {request.user} not authorized to reject {app}")
    return redirect('hrapplications:index')


@login_required
@permission_required('auth.human_resources')
def hr_application_search(request):
    logger.debug("hr_application_search called by user %s" % request.user)
    if request.method == 'POST':
        form = HRApplicationSearchForm(request.POST)
        logger.debug("Request type POST contains form valid: %s" % form.is_valid())
        if form.is_valid():
            searchstring = form.cleaned_data['search_string'].lower()
            applications = set()
            logger.debug(f"Searching for application with character name {searchstring} for user {request.user}")
            app_list = Application.objects.all()
            if not request.user.is_superuser:
                try:
                    app_list = app_list.filter(
                        form__corp__corporation_id=request.user.profile.main_character.corporation_id)
                except AttributeError:
                    logger.warning(
                        "User %s missing main character model: unable to filter applications to search" % request.user)

            applications = app_list.filter(

allianceauth/hrapplications/templates/hrapplications/corpchoice.html
{% extends "allianceauth/base-bs5.html" %}

{% load i18n %}

{% block page_title %}
    {% translate "Choose a Corp" %}
{% endblock page_title %}

{% block header_nav_brand %}
    {% translate "HR Application Management" %}
{% endblock header_nav_brand %}

{% block content %}
    <div>
        {% translate "Choose a Corp" as page_header %}
        {% include "framework/header/page-header.html" with title=page_header %}

        {% if choices %}
            <div class="card card-primary">
                <div class="card-header">
                    <div class="card-title mb-0">{% translate "Available Corps" %}</div>
                </div>

                <div class="card-body">
                    <table class="table table-responsive">
                        {% for choice in choices %}
                            <tr>
                                <td class="text-center">
                                    <a href="{% url 'hrapplications:create_view' choice.0 %}" class="btn btn-primary" title="Apply">{{ choice.1 }}</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        {% else %}
            <div class="alert alert-danger">{% translate "No corps are accepting applications at this time." %}</div>
        {% endif %}
    </div>
{% endblock content %}

allianceauth/hrapplications/templates/hrapplications/create.html
{% extends "allianceauth/base-bs5.html" %}
{% load django_bootstrap5 %}

{% load i18n %}

{% block page_title %}
    {% translate "Apply To" %} {{ corp.corporation_name }}
{% endblock page_title %}

{% block header_nav_brand %}
    {% translate "HR Application Management" %}
{% endblock header_nav_brand %}

{% block content %}
    <div>
        <h1 class="page-header text-center mb-3">
            {% translate "Apply To" %} {{ corp.corporation_name }}
        </h1>

        <div class="card">
            <div class="card-header">
                <div class="card-title mb-0">
                    {% translate "Application form" %}
                </div>
            </div>

            <div class="card-body">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <form method="post">
                            {% csrf_token %}

                            {% for question in questions %}
                                <div class="card mb-3 form-group border-0">
                                    <div class="card-header">
                                        <div class="card-title mb-0">{{ question.title }}</div>
                                    </div>

                                    <div class="card-body">
                                        {% if question.help_text %}
                                            <p class="text-muted">
                                                {{ question.help_text }}
                                            </p>
                                        {% endif %}

                                        {% for choice in question.choices.all %}
                                            <input type="{% if question.multi_select == False %}radio{% else %}checkbox{% endif %}" name="{{ question.pk }}" id="id_{{ question.pk }}_choice_{{ forloop.counter }}" value="{{ choice.choice_text }}">
                                            <label for="id_{{ question.pk }}_choice_{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                                        {% empty %}
                                            <textarea class="form-control" cols="30" id="id_{{ question.pk }}" name="{{ question.pk }}" rows="10"></textarea>
                                        {% endfor %}
                                    </div>
                                </div>
                            {% endfor %}

                            <div class="form-group clearfix">
                                {% translate "Submit" as button_text %}
                                {% bootstrap_button button_class="btn btn-primary" content=button_text name="submitApplicationForm" id="submitApplicationForm" %}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

allianceauth/hrapplications/templates/hrapplications/view.html
{% extends "allianceauth/base-bs5.html" %}

{% load django_bootstrap5 %}
{% load i18n %}

{% block page_title %}
    {% translate "View Application" %}
{% endblock page_title %}

{% block header_nav_brand %}
    {% translate "HR Application Management" %}
{% endblock header_nav_brand %}

{% block content %}
    <div>
        {% translate "View Application" as page_header %}
        {% include "framework/header/page-header.html" with title=page_header %}

        <div>
            {% if app.approved %}
                <div class="alert alert-success text-center">{% translate "Approved" %}</div>
            {% elif app.approved == False %}
                <div class="alert alert-danger text-center">{% translate "Denied" %}</div>
            {% else %}
                <div class="alert alert-warning text-center">{% translate "Pending" %}</div>
            {% endif %}

            {% if app.reviewer_str %}
                <div class="alert alert-info text-center">{% translate "Reviewer:" %} {{ app.reviewer_str }}</div>
            {% endif %}
        </div>

        <div class="card mb-3">
            <div class="card-header bg-info">
                <div class="card-title mb-0">{% translate "Applicant" %}</div>
            </div>

            <div class="card-body">
                <table class="table">
                    <tr>
                        <th class="text-center">{% translate "User" %}</th>
                        <th class="text-center">{% translate "Main Character" %}</th>
                    </tr>
                    <tr>
                        <td class="text-center">{{ app.user }}</td>
                        <td class="text-center">{{ app.main_character }}</td>
                    </tr>
                </table>
            </div>
        </div>

        <div class="card mb-3">
            <div class="card-header bg-info">
                <div class="card-title mb-0">{% translate "Characters" %}</div>
            </div>

            <div class="card-body">
                <table class="table">
                    <tr>
                        <th></th>
                        <th>{% translate "Name" %}</th>
                        <th>{% translate "Corporation" %}</th>
                        <th>{% translate "Alliance" %}</th>
                    </tr>

                    {% for char in app.characters %}
                        <tr>
                            <td>
                                <img class="ra-avatar img-responsive rounded-circle" src="{{ char.portrait_url_32 }}" alt="{{ char.character_name }}">
                            </td>
                            <td>{{ char.character_name }}</td>
                            <td>{{ char.corporation_name }}</td>
                            <td>{{ char.alliance_name }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>

        {% for response in responses %}
            <div class="card mb-3">
                <div class="card-header">
                    <div class="card-title mb-0">{{ response.question.title }}</div>
                </div>

                <div class="card-body">{{ response.answer|linebreaksbr }}</div>
            </div>
        {% endfor %}

        {% if buttons %}
            {% if perms.auth.human_resources %}
                <div class="card mb-3">
                    <div class="card-header">
                        <div class="card-title mb-0">{% translate "Actions" %}</div>
                    </div>

                    <div class="card-body text-center">
                        {% if app.approved == None %}
                            {% if app.reviewer == user %}
                                {% if perms.hrapplications.approve_application %}
                                    <a href="{% url 'hrapplications:approve' app.id %}" class="btn btn-success">{% translate "Approve" %}</a>
                                {% endif %}
                                {% if perms.hrapplications.reject_application %}
                                    <a href="{% url 'hrapplications:reject' app.id %}" class="btn btn-warning">{% translate "Reject" %}</a>
                                {% endif %}
                                {% if perms.hrapplications.delete_application %}
                                    <a href="{% url 'hrapplications:remove' app.id %}" class="btn btn-danger">{% translate "Delete" %}</a>
                                {% endif %}
                            {% elif not app.reviewer %}
                                <a href="{% url 'hrapplications:mark_in_progress' app.id %}" class="btn btn-warning">{% translate "Mark in Progress" %}</a>
                            {% endif %}
                        {% endif %}

                        {% if perms.hrapplications.add_applicationcomment %}
                            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-hr-comment">{% translate "Comment" %}</button>
                        {% endif %}
                    </div>
                </div>

                <div class="card-group" id="accordion" role="tablist" aria-multiselectable="true">
                    <div class="card card-default">
                        <div class="card-header">
                            <div class="card-title mb-0">
                                {% translate 'Comments' %} ({{ comments.count }})
                            </div>
                        </div>

                        <div class="card-body">
                            {% if comments %}
                                {% for comment in comments %}
                                    <div class="card card-default">
                                        <div class="card-header" role="tab" id="">
                                            <div class="card-title mb-0 clearfix">
                                                <div class="float-md-end">{{ comment.created }}</div>
                                                <div class="float-md-start">{% if comment.user.profile.main_character %}{{ comment.user.profile.main_character }}{% else %}{{ comment.user }}{% endif %}</div>
                                            </div>
                                        </div>
                                        <div class="card-body">{{ comment.text|linebreaks }}</div>
                                    </div>
                                {% endfor %}
                            {% else %}
                                <div class="alert alert-info">
                                    {% translate "No comments" %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endif %}
    </div>

    {% if perms.hrapplications.add_applicationcomment %}
        <div class="modal fade" id="modal-hr-comment" tabindex="-1" aria-labelledby="modalHrComment" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="modal-title fs-5" id="modalHrCommentLabel">
                            {% translate "Add Comment" %}
                        </div>

                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% translate 'Close' %}"></button>
                    </div>

                    <div class="modal-body">
                        <form class="form-signin" role="form" action="" method="POST">
                            {% csrf_token %}

                            {% bootstrap_form comment_form %}

                            <div class="form-group mt-3 clearfix">
                                {% translate "Add comment" as button_text %}
                                {% bootstrap_button button_class="btn btn-primary" content=button_text name="addComment" id="addComment" %}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}