allianceauth/groupmanagement/urls.py
from django.urls import path
from . import views

app_name = "groupmanagement"

urlpatterns = [
    # groups
    path("groups/", views.groups_view, name="groups"),
    path("group/request/join/<int:group_id>/", views.group_request_add, name="request_add"),
    path(
        "group/request/leave/<int:group_id>/", views.group_request_leave, name="request_leave"
    ),
    # group management
    path("groupmanagement/requests/", views.group_management, name="management"),
    path("groupmanagement/membership/", views.group_membership, name="membership"),
    path(
        "groupmanagement/membership/<int:group_id>/",
        views.group_membership_list,
        name="membership",
    ),
    path(
        "groupmanagement/membership/<int:group_id>/audit-log/",
        views.group_membership_audit,
        name="audit_log",
    ),
    path(
        "groupmanagement/membership/<int:group_id>/remove/<int:user_id>/",
        views.group_membership_remove,
        name="membership_remove",
    ),
    path(
        "groupmanagement/request/join/accept/<int:group_request_id>/",
        views.group_accept_request,
        name="accept_request",
    ),
    path(
        "groupmanagement/request/join/reject/<int:group_request_id>/",
        views.group_reject_request,
        name="reject_request",
    ),
    path(
        "groupmanagement/request/leave/accept/<int:group_request_id>/",
        views.group_leave_accept_request,
        name="leave_accept_request",
    ),
    path(
        "groupmanagement/request/leave/reject/<int:group_request_id>/",
        views.group_leave_reject_request,
        name="leave_reject_request",
    ),
]

allianceauth/urls.py
from typing import List, Iterable, Callable

from django.urls import include
import esi.urls
from django.conf import settings
from django.contrib import admin
from django.urls import URLPattern, include, path
from django.views.generic.base import TemplateView

import allianceauth.authentication.urls
import allianceauth.authentication.views
import allianceauth.groupmanagement.urls
import allianceauth.notifications.urls
import allianceauth.services.urls
from allianceauth import NAME, views
from allianceauth.authentication import hmac_urls
from allianceauth.authentication.decorators import (
    decorate_url_patterns,
    main_character_required
)
from allianceauth.hooks import get_hooks

admin.site.site_header = NAME


def urls_from_apps(
    apps_hook_functions: Iterable[Callable], public_views_allowed: List[str]
) -> List[URLPattern]:
    """Return urls from apps and add default decorators."""

    url_patterns = []
    allowed_apps = set(public_views_allowed)
    for app_hook_function in apps_hook_functions:
        url_hook = app_hook_function()
        app_pattern = url_hook.include_pattern
        excluded_views = (
            url_hook.excluded_views
            if app_pattern.app_name in allowed_apps
            else None
        )
        url_patterns += [
            path(
                "",
                decorate_url_patterns(
                    [app_pattern], main_character_required, excluded_views
                )
            )
        ]

    return url_patterns


# Functional/Untranslated URL's
urlpatterns = [
    # Locale
    path('i18n/', include('django.conf.urls.i18n')),

    # Authentication
    path('', include(allianceauth.authentication.urls)),
    path('account/login/', TemplateView.as_view(template_name='public/login.html'), name='auth_login_user'),
    path('account/', include(hmac_urls)),

    # Admin urls
    path('admin/', admin.site.urls),

    # SSO
    path('sso/', include((esi.urls, 'esi'), namespace='esi')),
    path('sso/login', allianceauth.authentication.views.sso_login, name='auth_sso_login'),

    # Notifications
    path('', include(allianceauth.notifications.urls)),

    # Groups
    path('', include(allianceauth.groupmanagement.urls)),

    # Services
    path('', decorate_url_patterns(allianceauth.services.urls.urlpatterns, main_character_required)),

    # Night mode
    path('night/', views.NightModeRedirectView.as_view(), name='nightmode'),

    # Theme Change
    path('theme/', views.ThemeRedirectView.as_view(), name='theme')
]

url_hooks = get_hooks("url_hook")
public_views_allows = getattr(settings, "APPS_WITH_PUBLIC_VIEWS", [])
urlpatterns += urls_from_apps(url_hooks, public_views_allows)

allianceauth/groupmanagement/forms.py
import functools

from django import forms
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.contrib.auth.models import Group, User
from django.core.exceptions import ValidationError
from django.db.models.functions import Lower
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from .models import ReservedGroupName


class GroupAdminForm(forms.ModelForm):
    users = forms.ModelMultipleChoiceField(
        queryset=User.objects.order_by(Lower('username')),
        required=False,
        widget=FilteredSelectMultiple(verbose_name=_("Users"), is_stacked=False),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance and self.instance.pk:
            self.fields["users"].initial = self.instance.user_set.all()

    def save(self, commit=True):
        group: Group = super().save(commit=False)

        if commit:
            group.save()

        users = self.cleaned_data["users"]
        if group.pk:
            self._save_m2m_and_users(group, users)
        else:
            self.save_m2m = functools.partial(
                self._save_m2m_and_users, group=group, users=users
            )

        return group

    def _save_m2m_and_users(self, group, users):
        """Save m2m relations incl. users."""
        group.user_set.set(users)
        self._save_m2m()

    def clean_name(self):
        my_name = self.cleaned_data['name']
        if ReservedGroupName.objects.filter(name__iexact=my_name).exists():
            raise ValidationError(
                _("This name has been reserved and can not be used for groups."),
                code='reserved_name'
            )
        return my_name


class ReservedGroupNameAdminForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['created_by'].initial = self.current_user.username
        self.fields['created_at'].initial = _("(auto)")

    created_by = forms.CharField(disabled=True)
    created_at = forms.CharField(disabled=True)

    def clean_name(self):
        my_name = self.cleaned_data['name'].lower()
        if Group.objects.filter(name__iexact=my_name).exists():
            raise ValidationError(
                _("There already exists a group with that name."), code='already_exists'
            )
        return my_name

    def clean_created_at(self):
        return now()

allianceauth/groupmanagement/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import Group
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.db.models import Count
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext_lazy as _

from allianceauth.notifications import notify

from .managers import GroupManager
from .models import GroupRequest, RequestLog

logger = logging.getLogger(__name__)


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_management(request):
    logger.debug("group_management called by user %s" % request.user)
    acceptrequests = []
    leaverequests = []

    base_group_query = GroupRequest.objects.select_related('user', 'group', 'user__profile__main_character')
    if GroupManager.has_management_permission(request.user):
        # Full access
        group_requests = base_group_query.all()
    else:
        # Group specific leader
        users__groups = GroupManager.get_group_leaders_groups(request.user)
        group_requests = base_group_query.filter(group__in=users__groups)

    for grouprequest in group_requests:
        if grouprequest.leave_request:
            leaverequests.append(grouprequest)
        else:
            acceptrequests.append(grouprequest)

    logger.debug("Providing user {} with {} acceptrequests and {} leaverequests.".format(
        request.user, len(acceptrequests), len(leaverequests)))

    show_leave_tab = (
        getattr(settings, 'GROUPMANAGEMENT_AUTO_LEAVE', False)
        and not GroupRequest.objects.filter(leave_request=True).exists()
    )

    render_items = {
        'acceptrequests': acceptrequests,
        'leaverequests': leaverequests,
        'show_leave_tab': show_leave_tab,
    }

    return render(request, 'groupmanagement/index.html', context=render_items)


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_membership(request):
    logger.debug("group_membership called by user %s" % request.user)
    # Get all open and closed groups
    if GroupManager.has_management_permission(request.user):
        # Full access
        groups = GroupManager.get_all_non_internal_groups()
    else:
        # Group leader specific
        groups = GroupManager.get_group_leaders_groups(request.user)

    groups = groups.exclude(authgroup__internal=True).annotate(num_members=Count('user')).order_by('name')

    render_items = {'groups': groups}

    return render(request, 'groupmanagement/groupmembership.html', context=render_items)


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_membership_audit(request, group_id):
    logger.debug("group_management_audit called by user %s" % request.user)
    group = get_object_or_404(Group, id=group_id)
    try:
        # Check its a joinable group i.e. not corp or internal
        # And the user has permission to manage it
        if not GroupManager.check_internal_group(group) or not GroupManager.can_manage_group(request.user, group):
            logger.warning(f"User {request.user} attempted to view the membership of group {group_id} but permission was denied")
            raise PermissionDenied

    except ObjectDoesNotExist:
        raise Http404("Group does not exist")
    render_items = {'group': group}
    entries = RequestLog.objects.filter(group=group).order_by('-date')
    render_items['entries'] = entries

    return render(request, 'groupmanagement/audit.html', context=render_items)


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_membership_list(request, group_id):
    logger.debug(
        "group_membership_list called by user %s "
        "for group id %s" % (request.user, group_id)
    )
    group = get_object_or_404(Group, id=group_id)
    try:

        # Check its a joinable group i.e. not corp or internal
        # And the user has permission to manage it
        if (not GroupManager.check_internal_group(group)
            or not GroupManager.can_manage_group(request.user, group)
        ):
            logger.warning(
                "User %s attempted to view the membership of group %s "
                "but permission was denied" % (request.user, group_id)
            )
            raise PermissionDenied

    except ObjectDoesNotExist:
        raise Http404("Group does not exist")

    group_leaders = group.authgroup.group_leaders.all()
    members = list()
    for member in \
        group.user_set\
            .all()\
            .select_related('profile', 'profile__main_character')\
            .order_by('profile__main_character__character_name'):

        members.append({
            'user': member,
            'main_char': member.profile.main_character,
            'is_leader': member in group_leaders
        })

    render_items = {'group': group, 'members': members}

    return render(
        request, 'groupmanagement/groupmembers.html',
        context=render_items
    )


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_membership_remove(request, group_id, user_id):
    logger.debug(f"group_membership_remove called by user {request.user} for group id {group_id} on user id {user_id}")
    group = get_object_or_404(Group, id=group_id)
    try:
        # Check its a joinable group i.e. not corp or internal
        # And the user has permission to manage it
        if not GroupManager.check_internal_group(group) or not GroupManager.can_manage_group(request.user, group):
            logger.warning(f"User {request.user} attempted to remove a user from group {group_id} but permission was denied")
            raise PermissionDenied

        try:
            user = group.user_set.get(id=user_id)
            request_info = user.username + ":" + group.name
            log = RequestLog(request_type=None,group=group,request_info=request_info,action=1,request_actor=request.user)
            log.save()
            # Remove group from user
            user.groups.remove(group)
            logger.info(f"User {request.user} removed user {user} from group {group}")
            messages.success(request, _("Removed user %(user)s from group %(group)s.") % {"user": user, "group": group})
        except ObjectDoesNotExist:
            messages.warning(request, _("User does not exist in that group"))

    except ObjectDoesNotExist:
        messages.warning(request, _("Group does not exist"))

    return redirect('groupmanagement:membership', group_id)


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_accept_request(request, group_request_id):
    logger.debug(f"group_accept_request called by user {request.user} for grouprequest id {group_request_id}")
    group_request = get_object_or_404(GroupRequest, id=group_request_id)
    try:
        group, created = Group.objects.get_or_create(name=group_request.group.name)

        if not GroupManager.joinable_group(group_request.group, group_request.user.profile.state) or \
                not GroupManager.can_manage_group(request.user, group_request.group):
            raise PermissionDenied

        group_request.user.groups.add(group)
        group_request.user.save()
        log = RequestLog(request_type=group_request.leave_request,group=group,request_info=group_request.__str__(),action=1,request_actor=request.user)
        log.save()
        group_request.delete()
        logger.info("User {} accepted group request from user {} to group {}".format(
            request.user, group_request.user, group_request.group.name))
        notify(group_request.user, "Group Application Accepted", level="success",
                message="Your application to %s has been accepted." % group_request.group)
        messages.success(request,
                        _('Accepted application from %(mainchar)s to %(group)s.') % {"mainchar": group_request.main_char, "group": group_request.group})

    except PermissionDenied as p:
        logger.warning(f"User {request.user} attempted to accept group join request {group_request_id} but permission was denied")
        raise p
    except:
        messages.error(request, _('An unhandled error occurred while processing the application from %(mainchar)s to %(group)s.') % {"mainchar": group_request.main_char, "group": group_request.group})
        logger.exception("Unhandled exception occurred while user {} attempting to accept grouprequest id {}.".format(
            request.user, group_request_id))
        pass

    return redirect("groupmanagement:management")


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_reject_request(request, group_request_id):
    logger.debug(f"group_reject_request called by user {request.user} for group request id {group_request_id}")
    group_request = get_object_or_404(GroupRequest, id=group_request_id)
    try:
        if not GroupManager.can_manage_group(request.user, group_request.group):
            raise PermissionDenied

        if group_request:
            logger.info("User {} rejected group request from user {} to group {}".format(
                request.user, group_request.user, group_request.group.name))
            log = RequestLog(request_type=group_request.leave_request,group=group_request.group,request_info=group_request.__str__(),action=0,request_actor=request.user)
            log.save()
            group_request.delete()
            notify(group_request.user, "Group Application Rejected", level="danger", message="Your application to %s has been rejected." % group_request.group)
            messages.success(request,
                            _('Rejected application from %(mainchar)s to %(group)s.') % {"mainchar": group_request.main_char, "group": group_request.group})

    except PermissionDenied as p:

allianceauth/groupmanagement/templates/groupmanagement/groupmembership.html
{% extends "allianceauth/base-bs5.html" %}
{% load static %}
{% load i18n %}
{% load navactive %}

{% block page_title %}{% translate "Groups Membership" %}{% endblock page_title %}
{% block header_nav_brand %}{% translate "Groups Membership" %}{% endblock header_nav_brand %}

{% block extra_css %}{% endblock extra_css %}

{% block header_nav_collapse_left %}
<li class="nav-item">
    <a class="nav-link {% navactive request 'groupmanagement:management' %}" href="{% url 'groupmanagement:management' %}">{% translate "Join/Leave Requests" %}</a>
</li>
{% endblock header_nav_collapse_left %}

{% block content %}
    {% if groups %}
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>{% translate "Name" %}</th>
                        <th>{% translate "Description" %}</th>
                        <th>{% translate "Status" %}</th>
                        <th style="white-space: nowrap;" class="text-center">{% translate "Member Count" %}</th>
                        <th style="min-width: 170px;"></th>
                    </tr>
                </thead>

                <tbody class="align-middle">
                    {% for group in groups %}
                        <tr>
                            <td>
                                <a href="{% url 'groupmanagement:membership' group.id %}">{{ group.name }}</a>
                            </td>

                            <td>{{ group.authgroup.description|linebreaks|urlize }}</td>

                            <td>
                                {% if group.authgroup.hidden %}
                                    <span class="badge bg-info">{% translate "Hidden" %}</span>
                                {% endif %}
                                {% if group.authgroup.open %}
                                    <span class="badge bg-success">{% translate "Open" %}</span>
                                {% else %}
                                    <span class="badge bg-secondary">{% translate "Requestable" %}</span>
                                {% endif %}
                            </td>

                            <td class="text-center">
                                {{ group.num_members }}
                            </td>

                            <td class="text-end">
                                <a href="{% url 'groupmanagement:membership' group.id %}" class="btn btn-primary" title="{% translate "View Members" %}">
                                    <i class="fa-regular fa-eye"></i>
                                </a>

                                <a href="{% url "groupmanagement:audit_log" group.id %}" class="btn btn-info" title="{% translate "Audit Members" %}">
                                    <i class="fa-regular fa-rectangle-list"></i>
                                </a>

                                <a id="clipboard-copy" data-clipboard-text="{{ request.scheme }}://{{request.get_host}}{% url 'groupmanagement:request_add' group.id %}" class="btn btn-warning" title="{% translate "Copy Direct Join Link" %}">
                                    <i class="fa-regular fa-clipboard"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="alert alert-warning text-center">
            {% translate "No groups to list." %}
        </div>
    {% endif %}
{% endblock content %}

{% block extra_javascript %}
    {% include "bundles/clipboard-js.html" %}

    <script>
        new ClipboardJS('#clipboard-copy');
    </script>
{% endblock extra_javascript %}

allianceauth/groupmanagement/templates/groupmanagement/index.html
{% extends "allianceauth/base-bs5.html" %}

{% load static %}
{% load i18n %}
{% load evelinks %}
{% load navactive %}

{% block page_title %}
    {% translate "Groups Management" %}
{% endblock page_title %}

{% block header_nav_brand %}
    {% translate "Groups Management" %}
{% endblock header_nav_brand %}

{% block header_nav_collapse_left %}
    <li class="active">
        <a class="nav-link active" id="add-tab" data-bs-toggle="tab" data-bs-target="#add" type="button" role="tab" aria-controls="add" aria-selected="true">
            {% translate "Join Requests" %}

            {% if acceptrequests %}
                <span class="badge bg-secondary">{{ acceptrequests|length }}</span>
            {% endif %}
        </a>
    </li>

    {% if not show_leave_tab %}
        <li>
            <a class="nav-link" id="leave-tab" data-bs-toggle="tab" data-bs-target="#leave" type="button" role="tab" aria-controls="leave" aria-selected="false">
                {% translate "Leave Requests" %}

                {% if leaverequests %}
                    <span class="badge bg-secondary">{{ leaverequests|length }}</span>
                {% endif %}
            </a>
        </li>
    {% endif %}

    <li class="nav-item ">
        <a class="nav-link {% navactive request 'groupmanagement:membership groupmanagement:audit_log' %}" href="{% url 'groupmanagement:membership' %}">
            {% translate "Group Membership" %}
        </a>
    </li>
{% endblock header_nav_collapse_left %}


{% block content %}
    <div class="tab-content">
        <div id="add" class="tab-pane active">
            {% if acceptrequests %}
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>{% translate "Character" %}</th>
                                <th>{% translate "Organization" %}</th>
                                <th>{% translate "Group" %}</th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody class="align-middle">
                            {% for acceptrequest in acceptrequests %}
                                <tr>
                                    <td>
                                        <img src="{{ acceptrequest.main_char|character_portrait_url:32 }}" class="rounded-circle" style="margin-right: 1rem;" alt="{{ acceptrequest.main_char.character_name }}">

                                        {% if acceptrequest.main_char %}
                                            <a href="{{ acceptrequest.main_char|evewho_character_url }}" target="_blank">
                                                {{ acceptrequest.main_char.character_name }}
                                            </a>
                                        {% else %}
                                            {{ acceptrequest.user.username }}
                                        {% endif %}
                                    </td>

                                    <td>
                                        {% if acceptrequest.main_char %}
                                            <a href="{{ acceptrequest.main_char|dotlan_corporation_url }}" target="_blank">
                                                {{ acceptrequest.main_char.corporation_name }}
                                            </a>
                                            <br>
                                            {{ acceptrequest.main_char.alliance_name|default_if_none:"" }}
                                        {% else %}
                                            {% translate "(unknown)" %}
                                        {% endif %}
                                    </td>

                                    <td>{{ acceptrequest.group.name }}</td>

                                    <td class="text-end">
                                        <a href="{% url 'groupmanagement:accept_request' acceptrequest.id %}" class="btn btn-success">
                                            {% translate "Accept" %}
                                        </a>
                                        <a href="{% url 'groupmanagement:reject_request' acceptrequest.id %}" class="btn btn-danger">
                                            {% translate "Reject" %}
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <div class="aa-callout aa-callout-warning text-center">
                    {% translate "No group add requests." %}
                </div>
            {% endif %}
        </div>

        {% if not show_leave_tab %}
            <div id="leave" class="tab-pane">
                {% if leaverequests %}
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>{% translate "Character" %}</th>
                                    <th>{% translate "Organization" %}</th>
                                    <th>{% translate "Group" %}</th>
                                    <th></th>
                                </tr>
                            </thead>

                            <tbody class="align-middle">
                                {% for leaverequest in leaverequests %}
                                    <tr>
                                        <td>
                                            <img src="{{ leaverequest.main_char|character_portrait_url:32 }}" class="rounded-circle" style="margin-right: 1rem;" alt="{{ leaverequest.main_char.character_name }}">

                                            {% if leaverequest.main_char %}
                                                <a href="{{ leaverequest.main_char|evewho_character_url }}" target="_blank">
                                                    {{ leaverequest.main_char.character_name }}
                                                </a>
                                            {% else %}
                                                {{ leaverequest.user.username }}
                                            {% endif %}
                                        </td>

                                        <td>
                                            {% if leaverequest.main_char %}
                                                <a href="{{ leaverequest.main_char|dotlan_corporation_url }}" target="_blank">
                                                    {{ leaverequest.main_char.corporation_name }}
                                                </a>
                                                <br>
                                                {{ leaverequest.main_char.alliance_name|default_if_none:"" }}
                                            {% else %}
                                                {% translate "(unknown)" %}
                                            {% endif %}
                                        </td>

                                        <td>{{ leaverequest.group.name }}</td>

                                        <td class="text-end">
                                            <a href="{% url 'groupmanagement:leave_accept_request' leaverequest.id %}" class="btn btn-success">
                                                {% translate "Accept" %}
                                            </a>

                                            <a href="{% url 'groupmanagement:leave_reject_request' leaverequest.id %}" class="btn btn-danger">
                                                {% translate "Reject" %}
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <div class="aa-callout aa-callout-warning text-center">{% translate "No group leave requests." %}</div>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock content %}

allianceauth/groupmanagement/templates/groupmanagement/menu.html
{% load i18n %}
{% load navactive %}


<li class="nav-item ">
    <a class="nav-link {% navactive request 'groupmanagement:management' %}" href="{% url 'groupmanagement:management' %}">{% translate "Group Requests" %}</a>
</li>
<li class="nav-item ">
    <a class="nav-link {% navactive request 'groupmanagement:membership groupmanagement:audit_log' %}" href="{% url 'groupmanagement:membership' %}">{% translate "Group Membership" %}</a>
</li>